name: Coverage

on:
  push:
    branches:
      - main

jobs:
  full-suite:
    runs-on: ubuntu-latest
    container: python:3.10.4-buster
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip3 install -r requirements/ci.txt

      - name: Run test with pytest
        run: coverage run -m pytest

      - name: Publish result to Code Climate
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage lcov
          debug: true
          prefix: ${{github.workspace}}/src
          coverageLocations: |
            ${{github.workspace}}/*.lcov:lcov
